# Generated by Django 4.0.3 on 2022-06-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appID', models.IntegerField()),
                ('url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('desc_snippet', models.TextField()),
                ('all_reviews', models.TextField()),
                ('popular_tags', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('appID', models.IntegerField()),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
